# Generated by Django 2.0.4 on 2018-07-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
        ('StartfeldSmartTshirtServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('classgroup', models.CharField(blank=True, max_length=21, null=True, verbose_name='Group or Class')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('assigned_device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StartfeldSmartTshirtServer.DeviceInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
