# Generated by Django 2.0.4 on 2019-02-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assigned_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StartfeldSmartTshirtServer.DeviceInfo'),
        ),
    ]
