# Generated by Django 2.0.4 on 2019-02-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190213_2008'),
        ('profiles', '0002_auto_20190210_2255'),
    ]

    operations = [
    ]
