# Generated by Django 2.0.4 on 2018-07-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklyBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('block_desc', models.CharField(max_length=200)),
                ('block_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('last_registered', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(null=True)),
            ],
        ),
    ]
